### ISSUE TITLE
Redundant wkbTypeFromDB2 functions

### ISSUE THREAD

**Issue by dwadler** [dwadler/QGIS#10]
QgsDb2TableModel::wkbTypeFromDb2 and QgsDb2Provider::getWkbType are virtually identical functions and only one should exist.

QgsDb2TableModel::wkbTypeFromDb2 is incorrect because it tries to determine whether the type is simple or 25D by checking names that don't exist in DB2 Spatial (POINTM, LINESTRINGM, etc).

QgsDb2Provider::getWkbType uses a dimension value which is always 2. I don't think the dimension can be determined until the data is actually read.

wkbType is a little confusing because there is both QGis::WkbType used in these classes and QgsWKBTypes::Type used in the geometry classes.  I don't know the difference or how/where the different types are used.

**Comment by Deegrin** [comment]
Whoa, didn't realize that.

> I don't think the dimension can be determined until the data is actually read.

Can we assume the dimension is always 2? The code seems to assume it.

If that's a valid assumption, I say we delete `QgsDb2Provider::getWkbType()` and change `QgsDb2TableModel::wkbTypeFromDb2` into something like:

    QGis::WkbType QgsDb2TableModel::wkbTypeFromDb2( QString type )
    {
      type = type.toUpper();
    
      if ( type == "ST_POINT" )
      {
        return QGis::WKBPoint;
      }
      else if ( type == "ST_MULTIPOINT" )
      {
        return QGis::WKBMultiPoint;
      }
      else if ( type == "ST_LINESTRING" )
      {
        return QGis::WKBLineString;
      }
      else if ( type == "ST_MULTILINESTRING" )
      {
        return QGis::WKBMultiLineString;
      }
      else if ( type == "ST_POLYGON" )
      {
        return QGis::WKBPolygon;
      }
      else if ( type == "ST_MULTIPOLYGON" )
      {
        return QGis::WKBMultiPolygon;
      }
      else if ( type == "NONE" )
      {
        return QGis::WKBNoGeometry;
      }
      else
      {
        return QGis::WKBUnknown;
      }
    }

Is this okay?

> wkbType is a little confusing because there is both QGis::WkbType used in these classes and QgsWKBTypes::Type used in the geometry classes. I don't know the difference or how/where the different types are used.

Me neither. But I don't think we have to worry about the difference as far as I can tell.

**Comment by dwadler** [comment]
It doesn't matter where the logic lives, but I would prefer to keep the dimension as a parameter and keep the 25D types.

One of the ways I've used to get the srid when a geometry column isn't registered is to query the data table and use ST_SRID to get the value for the first row. One could also use ST_DIMENSION to get the dimension.

**Comment by Deegrin** [comment]
Done. See the above commit reference.
