### ISSUE TITLE
Update DB2 icons for browser and add layer dialog

### ISSUE THREAD

**Issue by dwadler** [dwadler/QGIS#12]
I've updated mActionAddDb2Layer.svg and mIconDb2.svg to use a similar blue color scheme and also add the little "+" in the lower-right for the add layer icon.

Does anyone know what needs to be rebuilt to get this incorporated?  I've been doing a complete rebuild but this takes an hour or more.

Pushed changes.

**Comment by Deegrin** [comment]
> Does anyone know what needs to be rebuilt to get this incorporated? I've been doing a complete rebuild but this takes an hour or more.

I think you should be able to build the UNINSTALL and then the INSTALL project in Visual Studio to refresh the image. However, I didn't try this yet - had to do a complete rebuild for other reasons.

**Comment by redwoodxiao** [comment]
@dwadler , 

I think just target build-all-> install will work once you add to 
 C:\qgis_db2\QGISDB2\images\images.qrc(344):	
<file>themes/default/mIconDb2.svg</file>

**Comment by dwadler** [comment]
mIconDb2.svg is already in images.qrc.

When I right-click on ALL_BUILD, I don't get an "install" selection.
Or are you referring to something different.

I committed / pushed a bunch of minor changes without creating an issue - I've been building on Linux and there were a lot of minor warning messages that didn't appear on Windows.

The authentication changes are almost done - it is certainly interesting implementing something without any design documentation. Fortunately, with source code to look at it is possible to get things working.

**Comment by Deegrin** [comment]
Below ALL_BUILD, there's INSTALL. UNINSTALL is farther down the list.

![vs](https://cloud.githubusercontent.com/assets/1267190/13022872/d77cac9e-d198-11e5-8411-41a9621e8adc.jpg)

**Comment by dwadler** [comment]
I know, I use INSTALL all the time to update the DB2 provider DLL.
I thought you were referring to something different.
Do you know where the images/icons actually are in the runtime environment?

**Comment by Deegrin** [comment]
> I know, I use INSTALL all the time to update the DB2 provider DLL.
I thought you were referring to something different.

I meant that if you built the UNINSTALL project first then executed the INSTALL afterwards, it might refresh your image. However, if your QGIS installation already has the updated icons from the full rebuild, I guess we're fine.

> Do you know where the images/icons actually are in the runtime environment?

I've tried searching before with no luck. I can't tell if QGIS packages the images into one file, but it seems that way.

**Comment by redwoodxiao** [comment]
@dwadler 

I think if you just want to see how the icon look. You can put your icon in 

C:\Users\YOUR_USERNAME\.qgis2\themes\default\

when QGIS starts, it will look there for the icon. If it is not there, it will fall back to a compressed single file
Note that it is ".qgis2" folder

**Comment by dwadler** [comment]
How did you figure this out?

**Comment by redwoodxiao** [comment]
I traced the code to see where QGIS was reading files. That shows "themes\default\" folder. Then I search for themes default folder within the OS, and put some files there to see if QGIS read them.

**Comment by dwadler** [comment]
This seems to be working so closing the issue.
