### ISSUE TITLE
Conform to QGIS Coding Standards

### ISSUE THREAD

**Issue by Deegrin** [dwadler/QGIS#6]
See [the official coding standards guide](https://qgis.org/en/site/getinvolved/development/qgisdevelopersguide/codingstandards.html).

Looks like we mainly need:
- [x] standard header and license (done by @Deegrin)
- [x] tab spacing should be two spaces (done by @dwadler)
  - [x] provide instructions on how to set that in Visual Studio 2010
- [x] braces should start on the line following the expression (done by @dwadler)
- [x] execute the `scripts/prepare-commit.sh` script to convert to "astyle" (done by @dwadler)
- [x] API documentation

Please consider not mixing code/logic changes in the commits for this task for easy review.

Tab/indent settings in Visual Studio 2010 can be found in `Tools > Options > Text Editor > C/C++ > Tabs`. Set `Tab size` and `Indent size` to 2.

**Comment by Deegrin** [comment]
I used this as the license header, naming @dwadler as the primary author:

    /***************************************************************************
      qgsdb2provider.cpp - Data provider for DB2 server
      --------------------------------------
      Date      : 2016-01-27
      Copyright : (C) 2016 by David Adler
      Email     : dadler at adtechgeospatial.com
    /***************************************************************************
     *
     * This program is free software; you can redistribute it and/or modify
     * it under the terms of the GNU General Public License as published by
     * the Free Software Foundation; either version 2 of the License, or
     * (at your option) any later version.
     *
     ***************************************************************************/

**Comment by dwadler** [comment]
You and Shirley should get credit also - not sure how to indicate.

**Comment by Deegrin** [comment]
I asked the QGIS developers via [their Gitter](https://gitter.im/qgis/QGIS) and they seem to be fine with something along these lines:

    /***************************************************************************
      filename.cpp - description
      --------------------------------------
      Date      : 2016-01-31
      Copyright : (C) 2016 by Primary Contributor,
                              Secondary Contributor 1, Secondary Contributor 2
      Email     : primary@contributor.com
                  secondary1@contributor.com, secondary2@contributor.com
    /***************************************************************************

I'll make the change in a future commit.

**Comment by Deegrin** [comment]
Updated all license headers to this:

    /***************************************************************************
      qgsdb2provider.h - Data provider for DB2 server
      --------------------------------------
      Date      : 2016-01-27
      Copyright : (C) 2016 by David Adler
                              Shirley Xiao, David Nguyen
      Email     : dadler at adtechgeospatial.com
                  xiaoshir at us.ibm.com, nguyend at us.ibm.com
    /***************************************************************************

**Comment by dwadler** [comment]
Where are we on the e-mails used in the license headers?

**Comment by dwadler** [comment]
Should be done.  Non-conforming code copied from MSSQL provider not corrected - most cases are not using braces for single statement after an if statement.

Closing
