### ISSUE TITLE
Use QgsAuthManager to Get/Save Credentials

### ISSUE THREAD

**Issue by Deegrin** [dwadler/QGIS#8]
Use the QgsAuthManager class to get and save credentials. See [this pull request comment](https://github.com/qgis/QGIS/pull/2732).

**Comment by dwadler** [comment]
Along with this, we should probably change our connection dialog to look more like the dialog for PostGIS, with save buttons for Username and Password.
We should also remove the radio buttons for z/OS or LUW - this doesn't seem to be necessary.

Who can do this?

**Comment by redwoodxiao** [comment]
@dwadler I can work on this. :)

**Comment by Deegrin** [comment]
> We should also remove the radio buttons for z/OS or LUW - this doesn't seem to be necessary.

I agree we should remove the radio buttons for now. Perhaps we should just comment out the code that sets and saves `mEnvironment` if we're ever going to have geometryless table support (issue #1) and want to execute environment-specific queries. Otherwise, we can just have users create stored procedures like we've discussed before.

In any case, this is not a priority at the moment. I'm just putting this out there again. Sorry, haha.

**Comment by dwadler** [comment]
Agree

**Comment by Deegrin** [comment]
@dwadler, I looked into your earlier concern. Postgres/PostGIS shows this dialog if the user chooses to not save the password and they try to connect or load a saved project:

![password](https://cloud.githubusercontent.com/assets/1267190/12863715/c4c290dc-cc2f-11e5-9be5-69f4a0ab1217.jpg)

Our plugin doesn't do this, of course. I did a trace and looks like this task to utilize the `QgsAuthManager` will take care of this. It won't have to be a separate task.

In any case, I don't think we have to worry about it too much unless we're *that* close to doing another pull request.

**Comment by dwadler** [comment]
@redwoodxiao are you able to work on this?  If you are too busy, I can take a look.

**Comment by Deegrin** [comment]
@dwadler, I caught up to @redwoodxiao and she won't be able to get to this anytime soon. Feel free to assign this issue at your discretion.

**Comment by redwoodxiao** [comment]
@dwadler 
Sorry not reply to this sooner. I was caught up to work on a production issue. I might be a bit busy for a while. Thanks for your help.  Very appreciated!  :D

**Comment by dwadler** [comment]
I committed and pushed the authorization changes. It works pretty nicely although I'm not sure what "cancel" should do on the credential screen. Our design for the database setup and connection is quite different from PostGIS so it isn't quite as easy to have "cancel" bypass the database connection.

You need to run CMake again as an include directory was added.

There is also a configurations tab although I don't know what it is for. This will take some more research.

QgsAuthManager isn't actually used directly by the PostGIS support. QgsCredentials puts up the dialog and I think under the covers it uses QgsAuthManager .

**Comment by dwadler** [comment]
Pushed authentication changes.

The authentication support is a bit confusing to say the least.  I don't think QgsCredentials uses QgsAuthManager under the covers.

My understanding of how it works:

- When you create a new database connection, you can select the "Configurations" tab and add a new configuration. The first time you do this, you need to specify a "master" password that will be used later to access the encrypted userids and password. When you "Add" a configuration, you can specify the type. Right now, only "Basic" is supported. You can specify a userid and password which will be encrypted and stored in an sqllite database. You give it a user-friendly name like 'DB2-LUW' and it also assigns and authentication id which is a 7 character string.

- When a saved connection is used to populate the browser or add a layer, the settings for the connection are read and if an authentication id is found, a prompt is made for the master password. (Note that the master password can not be retrieved - if you lose it, none of your saved authentication configurations will be accessable).

- The authentication magic takes place in QgsDataSourceURI::connectionInfo which was not at all obvious. if the parameter expandAuthConfig to this method is true, it will use QgsAuthManager to use the configuration id to access the appropriate authentication like QgsBasicAuthMethod to get the stored and encrypted information and insert it into username and password fields in the connection information string which can then be used to make a database connection.

In implementing this support, I made some significant changes to the code to simplify and remove redundancy.

QgsDb2SourceSelect and QgsDb2DataItems both had similar logic to load the saved database connection settings and check for validity. I created the static method 
bool QgsDb2ConnectionItem::ConnInfoFromSettings(const QString connName,
                                            QString &connInfo, QString &errorMsg)
which can be used to load the settings, generate the connInfo string with all the parameters and also check that need parameters are specified.

In various places, all the individual connection values were passed around (dbname, port, service, etc) and used to call QgsDb2Plugin::GetDatabase. The were also variously used to construct connInfo and extracted from connInfo. I got rid of most of the saving of the individual connection values and just saved/passed the connInfo string.

I have not yet tested the error paths and think that this could be handled better.

I also synced our fork with the QGIS master and merged (I hope) all of their latest changes into db2-development.

Let me know if you see any problems in the code changes and in using it.

I'm not closing this issue until testing is done. I also need to see if we can add the additional authentication types and have them supported automatically.

**Comment by dwadler** [comment]
Something broke ;-)

The browser tree fills in ok but the layer doesn't display - the connection information got lost.

**Comment by dwadler** [comment]
Should all be fixed now.

**Comment by dwadler** [comment]
Implemented basic authentication. Closing
